# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Curtis Lab
email: brenda.curtis@nih.gov
description: > # this means to ignore newlines until "baseurl:"
  Website of the Curtis Lab.
baseurl: ""
url: ""

include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

domain: ttrucurtis.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://ttrucurtis.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl:       # place folder name if the site is served in a subfolder

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links
